### PR TITLE
Grunt multi sass theme support

### PR DESCRIPTION
**Pull request by lahmann**
Finally I found some time to test the current state of the grunt branch. It looks very good so far and I have only some few comments and suggestions:

1. Missing dependencies section in package.json:
Currently the compiled css files get committed which is fine and helpful for allowing to install VuFind as easy as possible (no need to compile the css upon installation) - therefore the devDependencies section in package.json suffices. However adding a dependencies section as well and moving the non-dev dependencies over there would allow to compile during production deploy and adding development/production relevant settings in the future.

2. `grunt-contrib-sass` vs. `grunt-sass`:
We are using [grunt-sass](https://github.com/sindresorhus/grunt-sass) which is libsass (Sass compiler in C++) based and fully [compatible](http://sass-compatibility.github.io/) to Sass. Although grunt-contrib-sass using the official Sass compiler would be preferable requiring Ruby for grunt-contrib-sass might cause some additional setup troubles. Therefore I would favor grunt-sass (should be faster too).

3. `sass_recursive`:
We have quite some cascades of themes which would add lots of complexity to our workflow if we would have to add those themes and folders to the Gruntfile.js by hand. Using the task `sass_recursive` allows to scan the themes folder and compile each scss file being found (or just a particular theme when passing the themes to be compiled as argument - e.g. `grunt sass_recursive:dist:bootstrap3`) in a `scss` folder.
If you agree that this task might be helpful for others there are still some small tasks todo:
  * [ ] agree upon folder names for scss files (scss vs. sass)
  * [ ] find a better name for `sass_recursive` (`sass_scan`?)

4. `grunt-contrib-watch` in devDependencies:
For development purposes grunt-contrib-watch is very handy as it compiles the css after each edit of the less/scss file. I have added a watch task to Gruntfile.js to watch scss files, this could be easily extended to watch less files as well.

### CODE REVIEW

**Comment by crhallberg** [comment]
This is really great advice! I'm working now to see if we can use some of the logic that Demian wrote for LESS to simplify things.

`grunt-sass` seems like a welcome change of libraries.

It seems like you prefer scss for folder names. Is that true? My only concern is that "sass" would more easily differentiate itself from "css", visually.

**Comment by lahmann** [comment]
Yes, we prefer "scss" as this foldername indicates what kind of files are to be expected (same as js, css, less etc.). Although I agree that sass would differentiate a bit more from css, I think the implicit convention to name the folders after the type of files to be expected should outweight this concern.

**Comment by crhallberg** [comment]
Ok, the new folder path is going to be `scss`.

**Comment by crhallberg** [comment]
All of the recommendations here have been incorporated into the [grunt PR](https://github.com/vufind-org/vufind/pull/659). Thank you for all the advice!

**Comment by lahmann** [comment]
Thanks, glad to help!

**Pull request closed without merging**
